name: Deploy to Server
on:
  push:
    branches: [ "main", "dev" ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Get GHCR image digest via API
        env:
          GH_USER: ${{ github.actor }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IMAGE_NAME: trsjucpai-wallet-worker
          TAG: dev
        run: |
          IMG_ACCESS_TOKEN=$(curl -s \
            -u "$GH_USER:$GH_TOKEN" \
            "https://ghcr.io/token?scope=repository=trsjucpai/${IMAGE_NAME}:pull" \
            | sed -n 's/.*"token":"\([^"]*\)".*/\1/p')
          digest=$(curl -s -H "Authorization: Bearer ${IMG_ACCESS_TOKEN}" \
            -H "Accept: application/vnd.oci.image.manifest.v1+json" \
            https://ghcr.io/v2/trsjucpai/${IMAGE_NAME}/manifests/${TAG})
          echo "Digest: $digest"
          echo "digest=$digest" >> $GITHUB_OUTPUT
      # 更新 chart
      - name: Checkout Helm chart repo
        uses: actions/checkout@v3
        with:
          repository: trsjucpai/trsjucpai-chart.git
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref_name }}
          path: chart-repo

      # 更新 digest
      - name: Update image digest in values.yaml
        run: |
          sed -i "s|tag: .*|tag: $TRSJUC_IMG_DIGEST|" chart-repo/$TRSJUC_ARTIFACT/values.yaml

      # 提交
      - name: Commit and push chart changes
        run: |
          cd chart-repo
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add values.yaml
          git commit -m "Update image digest ${{ steps.digest.outputs.TRSJUC_IMG_DIGEST }}"
          git push
